# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/data/Yandex.Disk/Catalog_SevoCrear/SelfDevelopment_Practice/Programming/C++/CPLUS-UI-ChatCPPTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/data/Yandex.Disk/Catalog_SevoCrear/SelfDevelopment_Practice/Programming/C++/build-CPLUS-UI-ChatCPPTest-Desktop-Debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/data/Yandex.Disk/Catalog_SevoCrear/SelfDevelopment_Practice/Programming/C++/build-CPLUS-UI-ChatCPPTest-Desktop-Debug/CMakeFiles /mnt/data/Yandex.Disk/Catalog_SevoCrear/SelfDevelopment_Practice/Programming/C++/build-CPLUS-UI-ChatCPPTest-Desktop-Debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/data/Yandex.Disk/Catalog_SevoCrear/SelfDevelopment_Practice/Programming/C++/build-CPLUS-UI-ChatCPPTest-Desktop-Debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Chat

# Build rule for target.
Chat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Chat
.PHONY : Chat

# fast build rule for target.
Chat/fast:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/build
.PHONY : Chat/fast

#=============================================================================
# Target rules for targets named translate_my_ru

# Build rule for target.
translate_my_ru: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 translate_my_ru
.PHONY : translate_my_ru

# fast build rule for target.
translate_my_ru/fast:
	$(MAKE) -f CMakeFiles/translate_my_ru.dir/build.make CMakeFiles/translate_my_ru.dir/build
.PHONY : translate_my_ru/fast

#=============================================================================
# Target rules for targets named translations

# Build rule for target.
translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 translations
.PHONY : translations

# fast build rule for target.
translations/fast:
	$(MAKE) -f CMakeFiles/translations.dir/build.make CMakeFiles/translations.dir/build
.PHONY : translations/fast

#=============================================================================
# Target rules for targets named Chat_autogen

# Build rule for target.
Chat_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Chat_autogen
.PHONY : Chat_autogen

# fast build rule for target.
Chat_autogen/fast:
	$(MAKE) -f CMakeFiles/Chat_autogen.dir/build.make CMakeFiles/Chat_autogen.dir/build
.PHONY : Chat_autogen/fast

Chat_autogen/mocs_compilation.o: Chat_autogen/mocs_compilation.cpp.o

.PHONY : Chat_autogen/mocs_compilation.o

# target to build an object file
Chat_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/Chat_autogen/mocs_compilation.cpp.o
.PHONY : Chat_autogen/mocs_compilation.cpp.o

Chat_autogen/mocs_compilation.i: Chat_autogen/mocs_compilation.cpp.i

.PHONY : Chat_autogen/mocs_compilation.i

# target to preprocess a source file
Chat_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/Chat_autogen/mocs_compilation.cpp.i
.PHONY : Chat_autogen/mocs_compilation.cpp.i

Chat_autogen/mocs_compilation.s: Chat_autogen/mocs_compilation.cpp.s

.PHONY : Chat_autogen/mocs_compilation.s

# target to generate assembly for a file
Chat_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/Chat_autogen/mocs_compilation.cpp.s
.PHONY : Chat_autogen/mocs_compilation.cpp.s

sources/CommandLineInterface.o: sources/CommandLineInterface.cpp.o

.PHONY : sources/CommandLineInterface.o

# target to build an object file
sources/CommandLineInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/CommandLineInterface.cpp.o
.PHONY : sources/CommandLineInterface.cpp.o

sources/CommandLineInterface.i: sources/CommandLineInterface.cpp.i

.PHONY : sources/CommandLineInterface.i

# target to preprocess a source file
sources/CommandLineInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/CommandLineInterface.cpp.i
.PHONY : sources/CommandLineInterface.cpp.i

sources/CommandLineInterface.s: sources/CommandLineInterface.cpp.s

.PHONY : sources/CommandLineInterface.s

# target to generate assembly for a file
sources/CommandLineInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/CommandLineInterface.cpp.s
.PHONY : sources/CommandLineInterface.cpp.s

sources/Database.o: sources/Database.cpp.o

.PHONY : sources/Database.o

# target to build an object file
sources/Database.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Database.cpp.o
.PHONY : sources/Database.cpp.o

sources/Database.i: sources/Database.cpp.i

.PHONY : sources/Database.i

# target to preprocess a source file
sources/Database.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Database.cpp.i
.PHONY : sources/Database.cpp.i

sources/Database.s: sources/Database.cpp.s

.PHONY : sources/Database.s

# target to generate assembly for a file
sources/Database.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Database.cpp.s
.PHONY : sources/Database.cpp.s

sources/Message.o: sources/Message.cpp.o

.PHONY : sources/Message.o

# target to build an object file
sources/Message.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Message.cpp.o
.PHONY : sources/Message.cpp.o

sources/Message.i: sources/Message.cpp.i

.PHONY : sources/Message.i

# target to preprocess a source file
sources/Message.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Message.cpp.i
.PHONY : sources/Message.cpp.i

sources/Message.s: sources/Message.cpp.s

.PHONY : sources/Message.s

# target to generate assembly for a file
sources/Message.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Message.cpp.s
.PHONY : sources/Message.cpp.s

sources/Parsing.o: sources/Parsing.cpp.o

.PHONY : sources/Parsing.o

# target to build an object file
sources/Parsing.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Parsing.cpp.o
.PHONY : sources/Parsing.cpp.o

sources/Parsing.i: sources/Parsing.cpp.i

.PHONY : sources/Parsing.i

# target to preprocess a source file
sources/Parsing.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Parsing.cpp.i
.PHONY : sources/Parsing.cpp.i

sources/Parsing.s: sources/Parsing.cpp.s

.PHONY : sources/Parsing.s

# target to generate assembly for a file
sources/Parsing.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Parsing.cpp.s
.PHONY : sources/Parsing.cpp.s

sources/Test.o: sources/Test.cpp.o

.PHONY : sources/Test.o

# target to build an object file
sources/Test.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Test.cpp.o
.PHONY : sources/Test.cpp.o

sources/Test.i: sources/Test.cpp.i

.PHONY : sources/Test.i

# target to preprocess a source file
sources/Test.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Test.cpp.i
.PHONY : sources/Test.cpp.i

sources/Test.s: sources/Test.cpp.s

.PHONY : sources/Test.s

# target to generate assembly for a file
sources/Test.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/Test.cpp.s
.PHONY : sources/Test.cpp.s

sources/User.o: sources/User.cpp.o

.PHONY : sources/User.o

# target to build an object file
sources/User.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/User.cpp.o
.PHONY : sources/User.cpp.o

sources/User.i: sources/User.cpp.i

.PHONY : sources/User.i

# target to preprocess a source file
sources/User.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/User.cpp.i
.PHONY : sources/User.cpp.i

sources/User.s: sources/User.cpp.s

.PHONY : sources/User.s

# target to generate assembly for a file
sources/User.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/User.cpp.s
.PHONY : sources/User.cpp.s

sources/loginform.o: sources/loginform.cpp.o

.PHONY : sources/loginform.o

# target to build an object file
sources/loginform.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/loginform.cpp.o
.PHONY : sources/loginform.cpp.o

sources/loginform.i: sources/loginform.cpp.i

.PHONY : sources/loginform.i

# target to preprocess a source file
sources/loginform.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/loginform.cpp.i
.PHONY : sources/loginform.cpp.i

sources/loginform.s: sources/loginform.cpp.s

.PHONY : sources/loginform.s

# target to generate assembly for a file
sources/loginform.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/loginform.cpp.s
.PHONY : sources/loginform.cpp.s

sources/mainwindow.o: sources/mainwindow.cpp.o

.PHONY : sources/mainwindow.o

# target to build an object file
sources/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/mainwindow.cpp.o
.PHONY : sources/mainwindow.cpp.o

sources/mainwindow.i: sources/mainwindow.cpp.i

.PHONY : sources/mainwindow.i

# target to preprocess a source file
sources/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/mainwindow.cpp.i
.PHONY : sources/mainwindow.cpp.i

sources/mainwindow.s: sources/mainwindow.cpp.s

.PHONY : sources/mainwindow.s

# target to generate assembly for a file
sources/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/mainwindow.cpp.s
.PHONY : sources/mainwindow.cpp.s

sources/registrationform.o: sources/registrationform.cpp.o

.PHONY : sources/registrationform.o

# target to build an object file
sources/registrationform.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/registrationform.cpp.o
.PHONY : sources/registrationform.cpp.o

sources/registrationform.i: sources/registrationform.cpp.i

.PHONY : sources/registrationform.i

# target to preprocess a source file
sources/registrationform.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/registrationform.cpp.i
.PHONY : sources/registrationform.cpp.i

sources/registrationform.s: sources/registrationform.cpp.s

.PHONY : sources/registrationform.s

# target to generate assembly for a file
sources/registrationform.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/registrationform.cpp.s
.PHONY : sources/registrationform.cpp.s

sources/sha1.o: sources/sha1.cpp.o

.PHONY : sources/sha1.o

# target to build an object file
sources/sha1.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/sha1.cpp.o
.PHONY : sources/sha1.cpp.o

sources/sha1.i: sources/sha1.cpp.i

.PHONY : sources/sha1.i

# target to preprocess a source file
sources/sha1.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/sha1.cpp.i
.PHONY : sources/sha1.cpp.i

sources/sha1.s: sources/sha1.cpp.s

.PHONY : sources/sha1.s

# target to generate assembly for a file
sources/sha1.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/sha1.cpp.s
.PHONY : sources/sha1.cpp.s

sources/startscreen.o: sources/startscreen.cpp.o

.PHONY : sources/startscreen.o

# target to build an object file
sources/startscreen.cpp.o:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/startscreen.cpp.o
.PHONY : sources/startscreen.cpp.o

sources/startscreen.i: sources/startscreen.cpp.i

.PHONY : sources/startscreen.i

# target to preprocess a source file
sources/startscreen.cpp.i:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/startscreen.cpp.i
.PHONY : sources/startscreen.cpp.i

sources/startscreen.s: sources/startscreen.cpp.s

.PHONY : sources/startscreen.s

# target to generate assembly for a file
sources/startscreen.cpp.s:
	$(MAKE) -f CMakeFiles/Chat.dir/build.make CMakeFiles/Chat.dir/sources/startscreen.cpp.s
.PHONY : sources/startscreen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Chat"
	@echo "... translate_my_ru"
	@echo "... translations"
	@echo "... Chat_autogen"
	@echo "... Chat_autogen/mocs_compilation.o"
	@echo "... Chat_autogen/mocs_compilation.i"
	@echo "... Chat_autogen/mocs_compilation.s"
	@echo "... sources/CommandLineInterface.o"
	@echo "... sources/CommandLineInterface.i"
	@echo "... sources/CommandLineInterface.s"
	@echo "... sources/Database.o"
	@echo "... sources/Database.i"
	@echo "... sources/Database.s"
	@echo "... sources/Message.o"
	@echo "... sources/Message.i"
	@echo "... sources/Message.s"
	@echo "... sources/Parsing.o"
	@echo "... sources/Parsing.i"
	@echo "... sources/Parsing.s"
	@echo "... sources/Test.o"
	@echo "... sources/Test.i"
	@echo "... sources/Test.s"
	@echo "... sources/User.o"
	@echo "... sources/User.i"
	@echo "... sources/User.s"
	@echo "... sources/loginform.o"
	@echo "... sources/loginform.i"
	@echo "... sources/loginform.s"
	@echo "... sources/mainwindow.o"
	@echo "... sources/mainwindow.i"
	@echo "... sources/mainwindow.s"
	@echo "... sources/registrationform.o"
	@echo "... sources/registrationform.i"
	@echo "... sources/registrationform.s"
	@echo "... sources/sha1.o"
	@echo "... sources/sha1.i"
	@echo "... sources/sha1.s"
	@echo "... sources/startscreen.o"
	@echo "... sources/startscreen.i"
	@echo "... sources/startscreen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

