// This file is autogenerated. Changes will be overwritten.
#include "EXY53EAHJJ/moc_loginform.cpp"
#include "EXY53EAHJJ/moc_mainwindow.cpp"
#include "EXY53EAHJJ/moc_registrationform.cpp"
#include "EXY53EAHJJ/moc_startscreen.cpp"
